from enum import Enum
from display import embeds

from display.message import Message


class AllStrings(Enum):
    """ List of different message strings available
    """

    REG_NOT_REGISTERED = Message("You are not registered!", embed=embeds.register_help)
    REG_IS_REGISTERED_OWN = Message("You are already registered with the following Jaeger characters: `{}`, `{}`, `{}`")
    REG_IS_REGISTERED_NOA = Message("You are already registered without a Jaeger account! If you have your own account, please re-register with your Jaeger characters.")
    REG_HELP = Message("Registration help:", embed=embeds.register_help)
    REG_NO_ACCOUNT = Message("You successfully registered without a Jaeger account!")
    REG_INVALID = Message("Invalid registration!", embed=embeds.register_help)
    REG_CHAR_NOT_FOUND = Message("Invalid registration! Character `{}` is not valid!", embed=embeds.register_help)
    REG_NOT_JAEGER = Message("Invalid registration! Character `{}` doesn't belong to Jaeger!", embed=embeds.register_help)
    REG_ALREADY_EXIST = Message("Invalid registration! Character `{}` is already registered by {}!")
    REG_MISSING_FACTION = Message("Invalid registration! Can't find a {} character in your list!", embed=embeds.register_help)
    REG_UPDATE_OWN = Message("You successfully updated your profile with the following Jaeger characters: `{}`, `{}`, `{}`")
    REG_UPDATE_NOA = Message("You successfully removed your Jaeger characters from your profile.")
    REG_WITH_CHARS = Message("You successfully registered with the following Jaeger characters: `{}`, `{}`, `{}`")
    REG_FROZEN = Message("You can't register while you're playing a match")
    REG_RULES = Message("{} You have accepted the rules, you may now register", embed=embeds.register_help)
    REG_NO_RULE = Message("You have to accept the rules before registering! Check <#{}>")
    REG_FROZEN_2 = Message("You can't remove your account while being in a match!")

    LB_OFFLINE = Message("You can't queue if your Discord status is offline/invisible!")
    LB_ALREADY_IN = Message("You are already in queue!")
    LB_IN_MATCH = Message("You are already in a match!")
    LB_ADDED = Message("You've been added to the queue!", embed=embeds.lobby_list)
    LB_REMOVED = Message("You've been removed from the queue!", embed=embeds.lobby_list)
    LB_NOT_IN = Message("You're not in queue!")
    LB_QUEUE = Message("Current players in queue:", embed=embeds.lobby_list)
    LB_FULL = Message("Lobby is already full! Waiting for a match to start...")
    LB_STUCK = Message("Lobby is full, but can't start a new match yet. Please wait...", ping=False)
    LB_STUCK_JOIN = Message("You can't join the lobby, it is already full!")
    LB_MATCH_STARTING = Message("Lobby full, match can start! Join <#{}> for team selection!", ping=False)
    LB_WENT_INACTIVE = Message("{} was removed from the lobby because they went offline!", embed=embeds.lobby_list)
    LB_CLEARED = Message("Lobby has been cleared!", embed=embeds.lobby_list)
    LB_EMPTY = Message("Lobby is already empty!")
    LB_NOTIFY = Message("{} queue is almost full, join to start a match!")
    LB_GET = Message("Restore the lobby with `=lobby restore {}`")

    PK_OVER = Message("The teams are already made. You can't pick!")
    PK_NO_LOBBIED = Message("You must first queue and wait for a match to begin. Check <#{}>")
    PK_WAIT_FOR_PICK = Message("You can't do that! Wait for a Team Captain to pick you!")
    PK_WRONG_CHANNEL = Message("You are in the wrong channel! Check <#{}> instead")
    PK_NOT_TURN = Message("It's not your turn!")
    PK_NOT_CAPTAIN = Message("You are not Team Captain!")
    PK_SHOW_TEAMS = Message("Match status:", embed=embeds.team_update)
    PK_HELP = Message("Picking help:", embed=embeds.match_help)
    PK_NO_ARG = Message("@ mention a player to pick!", embed=embeds.match_help)
    PK_TOO_MUCH = Message("You can't pick more than one player at the same time!")
    PK_INVALID = Message("You can't pick that player!")
    PK_OK = Message("Player picked! {} your turn, pick a player!", embed=embeds.team_update, ping=False)
    PK_OK_2 = Message("Player picked!", ping=False)
    PK_LAST = Message("Assigned {} to {}!")
    PK_OK_FACTION = Message("Teams are ready! {} pick a faction!", embed=embeds.team_update, ping=False)
    PK_NOT_VALID_FACTION = Message("Incorrect input! Pick a valid faction!", embed=embeds.match_help)
    PK_FACTION_OK = Message("{} chose {}!", ping=False)
    PK_FACTION_ALREADY = Message("Faction already picked by the other team!")
    PK_FACTION_OK_NEXT = Message("{} chose {}! {} pick a faction!", ping=False)
    PK_FACTION_CHANGED = Message("{} changed to {}!")
    PK_FACTION_NOT_PLAYER = Message("Pick a faction, not a player!", embed=embeds.match_help)
    PK_WAIT_MAP =  Message("{} {} Pick an available map!", ping=False, embed=embeds.map_pool)
    PK_MAP_OK_CONFIRM = Message("Picked **{}**! {} confirm with `=p confirm` if you agree")
    PK_OVER_READY = Message("Can't do that if your team is ready!")
    PK_NO_MAP = Message("No map selected!")
    PK_SHOW_REACT_MAP = Message("React with ⤾ to go back to map list",
                                 embed=embeds.map_pool,
                                 ping=False)
    PK_RESIGNED = Message("Successfully resigned! {} is the new captain for {}!", embed=embeds.team_update)
    PK_PICK_STARTED = Message("Can't do that, you already picked a player!")

    EXT_NOT_REGISTERED = Message("You are not registered! Check <#{}>")
    UNKNOWN_ERROR = Message("Something unexpected happened! Please try again or contact staff if it keeps happening.\nDetails: *{}*")
    STOP_SPAM = Message("Please avoid spamming!")
    HELP = Message("Available commands:", embed=embeds.auto_help)
    INVALID_COMMAND = Message("Invalid command! Type `=help` for the list of available commands.")
    WRONG_USAGE = Message("Wrong usage of the command `={}`!")
    WRONG_CHANNEL = Message("The command `={}` can only be used in {}")
    WRONG_CHANNEL_2 = Message("The command `={}` can't be used in {}")
    NO_PERMISSION = Message("The command `={}` can only be used by staff members!")
    CHANNEL_INIT = Message("`Bot init`: Correctly hooked in channel <#{}>")
    INVALID_STR = Message("You entered an invalid character! `{}`")
    API_ERROR = Message("Could not reach Planetside2 API, try again later!")
    GLOBAL_INFO = Message("Here is what's going on in POG at the moment:", embed=embeds.global_info)
    CHECK_ACCOUNT = Message("PIL accounts password got changed! Re-register in <#{}> to confirm you still have access to your account!", embed=embeds.pil_accounts)

    BOT_UNLOCKED = Message("Unlocked!")
    BOT_LOCKED = Message("Locked!")
    BOT_IS_LOCKED = Message("Bot is locked!")
    BOT_ALREADY = Message("Already {}!")
    BOT_VERSION = Message("Version `{}`, locked: `{}`")
    BOT_FROZEN = Message("Channel frozen!")
    BOT_UNFROZEN = Message("Channel unfrozen!")
    BOT_BP_OFF = Message("Ingame status check is now enabled!")
    BOT_BP_ON = Message("Ingame status check is now disabled!")

    MATCH_INIT = Message("{}\nMatch is ready, starting team selection...")
    MATCH_SHOW_PICKS = Message("Captains have been selected, {} choose a player", embed=embeds.team_update, ping=False)
    MATCH_MAP_AUTO = Message("Match will be on **{}**", ping=False)
    MATCH_CONFIRM = Message("{} {} Type `=ready` when your team is inside their sundy, ready to start",
                             embed=embeds.team_update)
    MATCH_NOT_READY = Message("You can't use command {}, the match is not ready to start!")
    MATCH_TEAM_READY = Message("{} is now ready!", embed=embeds.team_update)
    MATCH_TEAM_UNREADY = Message("{} is no longer ready!", embed=embeds.team_update)
    MATCH_STARTING_1 = Message("Everyone is ready, round {} is starting in {} seconds!\nAll players will be pinged on round start")
    MATCH_STARTING_2 = Message("Round {} is starting in {} seconds!")
    MATCH_STARTED = Message("{}\n{}\nRound {} is starting now!")
    MATCH_NO_MATCH = Message("Can't use command `={}`, no match is happening here!")
    MATCH_NO_COMMAND = Message("Can't use command `={}` now!")
    MATCH_CLEARED = Message("Successfully cleared!")
    MATCH_PLAYERS_NOT_READY = Message("Can't get {} ready, {} did not accept their Jaeger accounts", ping=False)
    MATCH_PLAYERS_OFFLINE = Message("Can't get {} ready, {} are not online in game!", ping=False, embed=embeds.offline_list)
    MATCH_CLEAR = Message("Clearing match...", ping=False)
    MATCH_MAP_SELECTED = Message("Successfully selected **{}**")
    MATCH_ROUND_OVER = Message("{}\n{}\nRound {} is over!")
    MATCH_OVER = Message("The match is over!\nClearing channel...")
    MATCH_ALREADY = Message("The match is already started!")
    MATCH_SWAP = Message("Swap sundy placement for the next round!")

    MAP_HELP = Message("Here is how to choose a map:", embed=embeds.map_help)
    MAP_TOO_MUCH = Message("Too many maps found! Try to be more precise")
    MAP_NOT_FOUND = Message("Couldn't find a result for your search!")
    MAP_DISPLAY_LIST = Message("Here are the maps found:", embed=embeds.selected_maps)
    MAP_SHOW_POOL = Message("Map list:", embed=embeds.selected_maps)
    MAP_SELECTED = Message("The current map is **{}**")
    MAP_BOOKED = Message("WARNING: **{}** is currently reserved in the Jaeger Calendar. Please check availability before confirming this map.",
                          embed=embeds.jaeger_calendar)

    MP_ADDED = Message("Added {} to the map pool")
    MP_REMOVED = Message("Removed {} from the map pool")

    ACC_NOT_ENOUGH = Message("Not enough accounts are available for this match!\n**Match has been canceled!**")
    ACC_ERROR = Message("Error when giving out Jaeger accounts!\n**Match has been canceled!**")
    ACC_UPDATE = Message(None, ping=False, embed=embeds.account)
    ACC_SENT = Message("**Successfully sent jaeger accounts  in DMs!**")
    ACC_SENDING = Message("Loading Jaeger accounts...")
    ACC_OVER = Message("Match is over, please log out of your Jaeger account!")
    ACC_CLOSED = Message("{}'s DMS are locked, can't send them a Jaeger account!")

    NOTIFY_REMOVED = Message("You left Notify!")
    NOTIFY_ADDED = Message("You joined Notify!")

    NOT_CODED = Message("The rest is not yet coded, work in progress. Clearing match...")

    RM_MENTION_ONE = Message("Invalid request! @ mention one player!")
    RM_NOT_IN_DB = Message("Can't find this player in the database!")
    RM_OK = Message("Player successfully removed from the system!")
    RM_IN_MATCH = Message("Can't remove a player who is in match!")
    RM_LOBBY = Message("{} have been removed by staff!", embed=embeds.lobby_list)
    RM_NOT_LOBBIED = Message("This player is not in queue!")
    RM_TIMEOUT = Message("{} will be muted from POG until {}!", ping=False)
    RM_TIMEOUT_FREE = Message("{} is no longer muted!", ping=False)
    RM_TIMEOUT_ALREADY = Message("Can't do that, player is not muted!")
    RM_TIMEOUT_HELP = Message("Command usage:", embed=embeds.timeout_help)
    RM_TIMEOUT_INVALID = Message("Invalid use of the command!", embed=embeds.timeout_help)
    RM_TIMEOUT_INFO = Message("Player is muted until {}!")
    RM_TIMEOUT_NO = Message("Player is not muted!")
    RM_DEMOTE_NO = Message("Can't demote this player!")
    RM_DEMOTE_OK = Message("Successfully demoted! {} is the new captain for {}!", ping=False)
    RM_DEMOTE_PICKING = Message("Can't demote a captain who has already started picking!")

    MUTE_SHOW = Message("You are muted from POG until {}!")
    MUTE_FREED = Message("You are no longer muted from POG!")

    SC_ILLEGAL_WE = Message("{} used {} during match {}! This weapon is banned! Ignoring {} kill(s)...")
    SC_PLAYERS_STRING = Message("Here is player data for squittal script:\n{}")
    SC_RESULT_HALF = Message("Match {} - **halftime**")
    SC_RESULT = Message("Match {}")

    SUB_NO = Message("This player can't be subbed!")
    SUB_NO_CAPTAIN = Message("Can't sub a Team Captain!")
    SUB_NO_PLAYER = Message("No player is available to substitute!")
    SUB_OKAY_TEAM = Message("{} replaced {} in {}", ping=False, embed=embeds.team_update)
    SUB_OKAY = Message("{} replaced {}!", ping=False, embed=embeds.team_update)
    SUB_LOBBY = Message("{} you have been designed as a substitute, join <#{}>!", embed=embeds.lobby_list)